export const defaultTours = [
  {
    id: '1',
    slug: 'hunza-valley-explorer',
    name: 'Hunza Valley Explorer',
    destination: 'Hunza, Gilgit-Baltistan',
    days: 7,
    duration: '7 Days / 6 Nights',
    startDate: 'Every Saturday',
    startTime: '06:00 AM',
    endDate: 'Following Friday',
    endTime: '08:00 PM',
    meetingPoint: 'Islamabad International Airport / Daewoo Terminal, Rawalpindi',
    description: 'Experience the majestic Karakoram peaks, ancient forts, and warm hospitality of Hunza.',
    fullDescription: 'Embark on an unforgettable 7-day journey through the legendary Hunza Valley, one of Pakistan\'s most breathtaking destinations. Nestled in the heart of the Karakoram Range, Hunza offers snow-capped peaks, turquoise lakes, ancient forts, and a rich cultural heritage that has captivated travelers for centuries.\n\nThis carefully curated tour takes you through Karimabad, Altit and Baltit forts, the stunning Attabad Lake, Passu Cones, and the iconic Hussaini Bridge. Enjoy warm local hospitality, traditional Hunza cuisine, and panoramic views that will stay with you forever.\n\nOur experienced guides ensure a safe, comfortable, and enriching experience — whether you\'re a first-time visitor or a returning explorer of Northern Pakistan.',
    highlights: [
      'Visit Baltit & Altit Forts',
      'Boat ride on Attabad Lake',
      'Eagle\'s Nest sunset viewpoint',
      'Karimabad bazaar & local cuisine',
      'Passu Cones & Hussaini Bridge',
    ],
    itinerary: [
      {
        day: 'Day 1',
        time: '06:00 AM',
        title: 'Islamabad to Chilas',
        activities: ['Pickup from Islamabad', 'Scenic drive via Karakoram Highway', 'Photo stops at viewpoints', 'Overnight stay in Chilas'],
      },
      {
        day: 'Day 2',
        time: '08:00 AM',
        title: 'Chilas to Karimabad, Hunza',
        activities: ['Continue on KKH to Hunza', 'Check-in at hotel', 'Evening walk in Karimabad bazaar'],
      },
      {
        day: 'Day 3',
        time: '09:00 AM',
        title: 'Baltit & Altit Forts',
        activities: ['Guided fort tours', 'Cultural heritage walk', 'Traditional lunch', 'Eagle\'s Nest sunset visit'],
      },
      {
        day: 'Day 4',
        time: '08:30 AM',
        title: 'Attabad Lake & Passu',
        activities: ['Boat ride on Attabad Lake', 'Visit Passu Cones', 'Hussaini Bridge photo session'],
      },
      {
        day: 'Day 5',
        time: '09:00 AM',
        title: 'Khunjerab Pass Excursion',
        activities: ['Drive to Khunjerab Pass (weather permitting)', 'Wildlife spotting', 'Return to Hunza'],
      },
      {
        day: 'Day 6',
        time: '10:00 AM',
        title: 'Free Day in Hunza',
        activities: ['Optional local village visit', 'Shopping & photography', 'Relax and enjoy mountain views'],
      },
      {
        day: 'Day 7',
        time: '07:00 AM',
        title: 'Return to Islamabad',
        activities: ['Early departure from Hunza', 'Arrive Islamabad by evening', 'Tour ends'],
      },
    ],
    price: 45000,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=1920&q=80',
  },
  {
    id: '2',
    slug: 'skardu-adventure',
    name: 'Skardu Adventure',
    destination: 'Skardu, Gilgit-Baltistan',
    days: 6,
    duration: '6 Days / 5 Nights',
    startDate: 'Every Friday',
    startTime: '05:30 AM',
    endDate: 'Following Wednesday',
    endTime: '09:00 PM',
    meetingPoint: 'Islamabad International Airport / Faisal Movers Terminal, Rawalpindi',
    description: 'Discover Deosai Plains, Shangrila Resort, and the gateway to K2 base camp.',
    fullDescription: 'Explore the gateway to the Karakoram on this thrilling 6-day Skardu adventure. Skardu is the launching point for expeditions to K2 and home to some of the most stunning landscapes in Pakistan — from the endless plains of Deosai to the crystal waters of Kachura Lake.\n\nVisit the iconic Shangrila Resort, explore Upper and Lower Kachura lakes, drive through Deosai National Park (the Land of Giants), and discover the ancient Kharpocho Fort overlooking the Indus River.\n\nThis tour is perfect for nature lovers, photographers, and adventure seekers who want to experience the raw beauty of Gilgit-Baltistan with expert local guidance and comfortable accommodations.',
    highlights: [
      'Deosai National Park safari',
      'Shangrila Resort & Lower Kachura Lake',
      'Upper Kachura Lake visit',
      'Skardu city & Kharpocho Fort',
      'Cold Desert of Skardu',
    ],
    itinerary: [
      {
        day: 'Day 1',
        time: '05:30 AM',
        title: 'Islamabad to Chilas',
        activities: ['Early morning departure', 'KKH scenic drive', 'Overnight in Chilas'],
      },
      {
        day: 'Day 2',
        time: '08:00 AM',
        title: 'Chilas to Skardu',
        activities: ['Drive to Skardu valley', 'Hotel check-in', 'Evening at Satpara Lake'],
      },
      {
        day: 'Day 3',
        time: '09:00 AM',
        title: 'Shangrila & Kachura Lakes',
        activities: ['Shangrila Resort visit', 'Lower Kachura Lake boating', 'Upper Kachura Lake hike'],
      },
      {
        day: 'Day 4',
        time: '07:00 AM',
        title: 'Deosai National Park',
        activities: ['Full-day Deosai safari', 'Wildlife & wildflower spotting', 'Return to Skardu'],
      },
      {
        day: 'Day 5',
        time: '10:00 AM',
        title: 'Skardu City Tour',
        activities: ['Kharpocho Fort visit', 'Cold Desert excursion', 'Local market exploration'],
      },
      {
        day: 'Day 6',
        time: '06:00 AM',
        title: 'Return to Islamabad',
        activities: ['Early departure', 'Arrive Islamabad by night', 'Tour concludes'],
      },
    ],
    price: 52000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1920&q=80',
  },
  {
    id: '3',
    slug: 'naran-kaghan-getaway',
    name: 'Naran Kaghan Getaway',
    destination: 'Naran, KPK',
    days: 5,
    duration: '5 Days / 4 Nights',
    startDate: 'Every Thursday',
    startTime: '07:00 AM',
    endDate: 'Following Monday',
    endTime: '07:00 PM',
    meetingPoint: 'Daewoo Terminal, Rawalpindi / Islamabad Pickup Point',
    description: 'Visit Lake Saif ul Malook, Babusar Top, and the lush green valleys of Kaghan.',
    fullDescription: 'A perfect 5-day escape to the Kaghan Valley — one of Pakistan\'s most beloved hill destinations. This tour covers the legendary Saif ul Malook Lake, the breathtaking Babusar Pass, Lulusar Lake, and the charming town of Naran surrounded by pine forests and snow-capped peaks.\n\nIdeal for families, couples, and groups, this getaway combines scenic drives, lake excursions, and comfortable hotel stays. Experience the magic of Kaghan Valley with professional guides who know every hidden gem along the way.',
    highlights: [
      'Lake Saif ul Malook excursion',
      'Babusar Top scenic drive',
      'Lulusar Lake stopover',
      'Naran & Kaghan valley exploration',
      'River-side camping experience',
    ],
    itinerary: [
      {
        day: 'Day 1',
        time: '07:00 AM',
        title: 'Islamabad to Naran',
        activities: ['Depart from Rawalpindi', 'Drive through Balakot & Kaghan', 'Check-in at Naran hotel'],
      },
      {
        day: 'Day 2',
        time: '08:00 AM',
        title: 'Saif ul Malook Lake',
        activities: ['Jeep ride to the lake', 'Full day at Saif ul Malook', 'Photography & boating'],
      },
      {
        day: 'Day 3',
        time: '09:00 AM',
        title: 'Lulusar Lake & Babusar Top',
        activities: ['Scenic drive to Lulusar Lake', 'Babusar Pass visit (seasonal)', 'Return to Naran'],
      },
      {
        day: 'Day 4',
        time: '10:00 AM',
        title: 'Free Day in Naran',
        activities: ['Optional hiking', 'Local bazaar visit', 'River-side relaxation'],
      },
      {
        day: 'Day 5',
        time: '07:00 AM',
        title: 'Return to Islamabad',
        activities: ['Morning departure', 'Arrive Rawalpindi by evening'],
      },
    ],
    price: 28000,
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=80',
  },
  {
    id: '4',
    slug: 'swat-valley-retreat',
    name: 'Swat Valley Retreat',
    destination: 'Swat, KPK',
    days: 4,
    duration: '4 Days / 3 Nights',
    startDate: 'Every Wednesday',
    startTime: '08:00 AM',
    endDate: 'Following Saturday',
    endTime: '06:00 PM',
    meetingPoint: 'Daewoo Terminal, Rawalpindi / Mingora Pickup Available',
    description: 'Explore the Switzerland of Pakistan with waterfalls, lakes, and scenic meadows.',
    fullDescription: 'Discover the emerald beauty of Swat Valley in 4 unforgettable days. Known as the "Switzerland of Pakistan," Swat enchants visitors with its lush green valleys, crystal-clear rivers, ancient Buddhist heritage, and the stunning Mahodand Lake.\n\nThis retreat includes visits to Malam Jabba, Mingora, Saidu Sharif, and the archaeological sites of Butkara Stupa. Perfect for a short but immersive trip into one of KPK\'s most picturesque regions.',
    highlights: [
      'Malam Jabba scenic visit',
      'Mahodand Lake day trip',
      'Mingora & Saidu Sharif city tour',
      'Buddhist archaeological sites',
      'River-side resort stay',
    ],
    itinerary: [
      {
        day: 'Day 1',
        time: '08:00 AM',
        title: 'Islamabad to Swat',
        activities: ['Drive through Malakand Pass', 'Arrive in Mingora', 'Hotel check-in & rest'],
      },
      {
        day: 'Day 2',
        time: '09:00 AM',
        title: 'Malam Jabba & Saidu Sharif',
        activities: ['Malam Jabba visit', 'Saidu Sharif exploration', 'White Palace photo stop'],
      },
      {
        day: 'Day 3',
        time: '07:30 AM',
        title: 'Mahodand Lake Excursion',
        activities: ['Jeep ride to Mahodand Lake', 'Full day lakeside picnic', 'Return to Mingora'],
      },
      {
        day: 'Day 4',
        time: '08:00 AM',
        title: 'Return to Islamabad',
        activities: ['Morning departure from Swat', 'Arrive Rawalpindi by evening'],
      },
    ],
    price: 32000,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1920&q=80',
  },
]

export const defaultHotels = [
  {
    id: '1',
    name: 'Serena Hotel Gilgit',
    location: 'Gilgit, Gilgit-Baltistan',
    rating: 4.8,
    pricePerNight: 15000,
    description: 'Luxury accommodation with stunning mountain views and world-class amenities.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
  },
  {
    id: '2',
    name: 'Eagle Nest Resort',
    location: 'Duikar, Hunza',
    rating: 4.9,
    pricePerNight: 12000,
    description: 'Breathtaking sunrise views over Rakaposhi and Ultar Sar peaks.',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
  },
  {
    id: '3',
    name: 'Shangrila Resort',
    location: 'Skardu',
    rating: 4.7,
    pricePerNight: 18000,
    description: 'Iconic resort on Lower Kachura Lake with heart-shaped lake views.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
  },
  {
    id: '4',
    name: 'Pearl Continental Murree',
    location: 'Murree, Punjab',
    rating: 4.6,
    pricePerNight: 10000,
    description: 'Premium hill station hotel surrounded by pine forests and cool mountain air.',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
  },
]

export const popularPlaces = [
  {
    id: 'hunza',
    name: 'Hunza',
    description: 'Ancient forts, cherry blossoms, and the legendary Karakoram Highway.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
  },
  {
    id: 'skardu',
    name: 'Skardu',
    description: "Gateway to the world's highest peaks and crystal-clear alpine lakes.",
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: 'naran',
    name: 'Naran',
    description: 'Home to the legendary Saif ul Malook Lake and Babusar Pass.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
  },
  {
    id: 'swat',
    name: 'Swat',
    description: 'Emerald valleys, Buddhist heritage, and the Malam Jabba ski resort.',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
  },
  {
    id: 'murree',
    name: 'Murree',
    description: "Pakistan's favorite hill station with colonial charm and pine forests.",
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
  },
  {
    id: 'fairy-meadows',
    name: 'Fairy Meadows',
    description: 'A magical meadow at the base of Nanga Parbat, the Killer Mountain.',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
  },
  {
    id: 'nanga-parbat',
    name: 'Nanga Parbat',
    description: 'The ninth highest mountain in the world with dramatic alpine scenery.',
    image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&q=80',
  },
]

export const features = [
  { icon: '🛡️', title: 'Trusted Travel Services', description: 'Licensed and verified travel agency with years of experience.' },
  { icon: '🧭', title: 'Experienced Tour Guides', description: 'Local experts who know every trail, culture, and hidden gem.' },
  { icon: '🎒', title: 'Best Tour Packages', description: "Curated itineraries covering Pakistan's most stunning destinations." },
  { icon: '🏨', title: 'Comfortable Hotels', description: 'Handpicked accommodations for a restful stay after adventure.' },
  { icon: '💰', title: 'Affordable Prices', description: 'Competitive rates without compromising on quality or comfort.' },
  { icon: '📞', title: '24/7 Customer Support', description: 'Round-the-clock assistance before, during, and after your trip.' },
]

export const reviews = [
  {
    id: '1',
    name: 'Ahmed Khan',
    rating: 5,
    text: 'Pehchaan Travels made our Hunza trip absolutely unforgettable. Everything was perfectly organized!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  },
  {
    id: '2',
    name: 'Fatima Ali',
    rating: 5,
    text: 'Professional team, great hotels, and amazing tour guides. Highly recommend for Northern Pakistan tours.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
  },
  {
    id: '3',
    name: 'Usman Malik',
    rating: 4,
    text: 'Custom trip to Skardu was exactly what we wanted. Pehchaan Travels listened to every detail.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
  },
]

export const HERO_IMAGE = 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1920&q=80'
export const TRIP_IMAGE = 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=1920&q=80'
export const PHONE_NUMBER = '+92 3264828913'
export const EMAIL = 'info@pehchaantravels.com'
export const ADDRESS = 'Main Boulevard, Islamabad, Pakistan'
