export const defaultTours = [
  {
    id: '1',
    slug: 'skardu-expedition',
    name: 'Skardu Expedition',
    destination: 'Skardu, Gilgit-Baltistan',
    days: 7,
    duration: '7 Days',
    startDate: 'Every Saturday',
    startTime: '06:00 AM',
    endDate: 'Following Friday',
    endTime: '08:00 PM',
    meetingPoint: 'Islamabad International Airport / Skardu Airport',
    description: 'Experience the mesmerizing Shangrila Resort, cold desert, and towering peaks of Skardu.',
    fullDescription: 'Experience the mesmerizing Shangrila Resort, cold desert, and towering peaks of Skardu on this 7-day expedition into Gilgit-Baltistan.\n\nVisit Lower and Upper Kachura Lakes, explore the mythical Deosai National Park, witness the incredible Cold Desert of Sarfaranga, and take in the sheer majesty of the Karakoram range.\n\nOur expert guides ensure an unforgettable and comfortable journey with handpicked accommodations and private transport.',
    highlights: [
      'Shangrila Resort & Kachura Lakes',
      'Deosai National Park safari',
      'Sarfaranga Cold Desert & dunes',
      'Kharpocho Fort & Skardu bazaar',
      'Mantoka Waterfall & Shigar Valley',
    ],
    itinerary: [
      { day: 'Day 1', time: '06:00 AM', title: 'Islamabad to Skardu', activities: ['Scenic flight or KKH drive to Skardu', 'Hotel check-in', 'Evening walk by Kachura lake'] },
      { day: 'Day 2', time: '08:30 AM', title: 'Shangrila Resort & Upper Kachura', activities: ['Shangrila resort tour', 'Boating on Upper Kachura Lake', 'Lakeside lunch'] },
      { day: 'Day 3', time: '07:30 AM', title: 'Deosai National Park Safari', activities: ['Full day safari in Deosai Plains', 'Sheosar Lake visit', 'Wildlife spotting'] },
      { day: 'Day 4', time: '09:00 AM', title: 'Shigar Valley & Fort', activities: ['Visit historic Shigar Fort', 'Blind Lake stopover', 'Local craft shopping'] },
      { day: 'Day 5', time: '09:30 AM', title: 'Sarfaranga Cold Desert', activities: ['Explore the Cold Desert', 'Dune quad biking', 'Sunset photography'] },
      { day: 'Day 6', time: '10:00 AM', title: 'Kharpocho Fort & Free Day', activities: ['Hike to Kharpocho Fort', 'Skardu local bazaar', 'Cultural dinner'] },
      { day: 'Day 7', time: '07:00 AM', title: 'Return Journey', activities: ['Depart from Skardu', 'Arrive in Islamabad', 'Tour concludes'] },
    ],
    price: 450,
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1000&q=80',
  },
  {
    id: '2',
    slug: 'autumn-in-hunza',
    name: 'Autumn in Hunza',
    destination: 'Hunza, Gilgit-Baltistan',
    days: 5,
    duration: '5 Days',
    startDate: 'Every Friday',
    startTime: '05:30 AM',
    endDate: 'Following Tuesday',
    endTime: '08:00 PM',
    meetingPoint: 'Islamabad Pickup Point / Gilgit Airport',
    description: 'Witness the magical colors of autumn in the heart of the Karakoram range.',
    fullDescription: 'Witness the magical colors of autumn in the heart of the Karakoram range. During autumn, the Hunza Valley transforms into a breathtaking tapestry of gold, amber, and crimson set against snow-capped peaks and azure skies.\n\nExplore Karimabad, Baltit & Altit Forts, Attabad Lake, and the majestic Passu Cones during the most photogenic season of the year.',
    highlights: [
      'Golden autumn foliage throughout Hunza',
      'Baltit & Altit Forts exploration',
      'Attabad Lake turquoise boat excursion',
      'Passu Cones & Hussaini Suspension Bridge',
      'Eagle\'s Nest panoramic viewpoint',
    ],
    itinerary: [
      { day: 'Day 1', time: '06:00 AM', title: 'Islamabad to Gilgit / Hunza', activities: ['Drive or fly to Gilgit', 'Scenic drive into Hunza Valley', 'Evening at Karimabad'] },
      { day: 'Day 2', time: '09:00 AM', title: 'Baltit & Altit Forts', activities: ['Guided tour of ancient forts', 'Autumn orchards walk', 'Eagle\'s Nest sunset'] },
      { day: 'Day 3', time: '08:30 AM', title: 'Attabad Lake & Passu', activities: ['Boat ride on Attabad Lake', 'Passu Cones photography', 'Hussaini Bridge experience'] },
      { day: 'Day 4', time: '09:00 AM', title: 'Khunjerab Pass / Upper Hunza', activities: ['Drive towards Khunjerab Pass', 'Local village culture', 'Traditional dinner'] },
      { day: 'Day 5', time: '07:00 AM', title: 'Return Journey', activities: ['Morning departure', 'Return to Islamabad', 'Tour concludes'] },
    ],
    price: 320,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1476820865390-c52aeebb9891?w=1000&q=80',
  },
  {
    id: '3',
    slug: 'fairy-meadows-trek',
    name: 'Fairy Meadows Trek',
    destination: 'Fairy Meadows, Gilgit-Baltistan',
    days: 6,
    duration: '6 Days',
    startDate: 'Every Wednesday',
    startTime: '05:00 AM',
    endDate: 'Following Monday',
    endTime: '09:00 PM',
    meetingPoint: 'Islamabad International Airport / Raikot Bridge',
    description: 'An adventurous trek to the base camp of the Killer Mountain, Nanga Parbat.',
    fullDescription: 'An adventurous trek to the base camp of the Killer Mountain, Nanga Parbat (8,126m). Fairy Meadows offers one of the most spellbinding alpine landscapes on Earth — lush green meadows surrounded by dense pine forests and the colossal ice-clad wall of Nanga Parbat looming right before your eyes.\n\nExperience exhilarating 4x4 jeep rides from Raikot Bridge, trekking through pristine alpine forests, cozy wooden cottage stays, and hikes to Beyal Camp and Nanga Parbat Base Camp.',
    highlights: [
      'Unmatched close-up views of Nanga Parbat (8,126m)',
      'Adventurous 4x4 Jeep ride on the Raikot track',
      'Trek to Beyal Camp & Nanga Parbat Base Camp',
      'Stargazing and bonfires at Fairy Meadows',
      'Wooden cabin lodging amidst alpine greenery',
    ],
    itinerary: [
      { day: 'Day 1', time: '05:00 AM', title: 'Islamabad to Chilas', activities: ['Departure via Karakoram Highway', 'Scenic mountain viewpoints', 'Overnight stay in Chilas'] },
      { day: 'Day 2', time: '07:30 AM', title: 'Raikot Bridge to Fairy Meadows', activities: ['Jeep ride to Tato village', 'Trek to Fairy Meadows', 'Check-in to wooden huts'] },
      { day: 'Day 3', time: '08:30 AM', title: 'Fairy Meadows & Reflection Lake', activities: ['Explore lush green meadows', 'Visit Reflection Lake', 'Spectacular views of Nanga Parbat'] },
      { day: 'Day 4', time: '08:00 AM', title: 'Beyal Camp & Base Camp Hike', activities: ['Hike to Beyal Camp', 'Optional trek to Base Camp', 'Return to Fairy Meadows'] },
      { day: 'Day 5', time: '08:00 AM', title: 'Trek Down to Raikot & Chilas', activities: ['Trek back to Tato', 'Jeep ride to Raikot Bridge', 'Overnight stay in Chilas / Besham'] },
      { day: 'Day 6', time: '07:00 AM', title: 'Return to Islamabad', activities: ['Drive back to Islamabad', 'Arrive by evening', 'Tour ends'] },
    ],
    price: 380,
    rating: 5.0,
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1000&q=80',
  },
  {
    id: '4',
    slug: 'swat-valley-retreat',
    name: 'Swat Valley Retreat',
    destination: 'Swat, KPK',
    days: 4,
    duration: '4 Days / 3 Nights',
    startDate: 'Every Wednesday',
    startTime: '08:00 AM',
    endDate: 'Following Saturday',
    endTime: '06:00 PM',
    meetingPoint: 'Daewoo Terminal, Rawalpindi / Mingora Pickup Available',
    description: 'Explore the Switzerland of Pakistan with waterfalls, lakes, and scenic meadows.',
    fullDescription: 'Discover the emerald beauty of Swat Valley in 4 unforgettable days. Known as the "Switzerland of Pakistan," Swat enchants visitors with its lush green valleys, crystal-clear rivers, ancient Buddhist heritage, and the stunning Mahodand Lake.\n\nThis retreat includes visits to Malam Jabba, Mingora, Saidu Sharif, and the archaeological sites of Butkara Stupa.',
    highlights: [
      'Malam Jabba scenic visit',
      'Mahodand Lake day trip',
      'Mingora & Saidu Sharif city tour',
      'Buddhist archaeological sites',
      'River-side resort stay',
    ],
    itinerary: [
      { day: 'Day 1', time: '08:00 AM', title: 'Islamabad to Swat', activities: ['Drive through Malakand Pass', 'Arrive in Mingora', 'Hotel check-in & rest'] },
      { day: 'Day 2', time: '09:00 AM', title: 'Malam Jabba & Saidu Sharif', activities: ['Malam Jabba visit', 'Saidu Sharif exploration', 'White Palace photo stop'] },
      { day: 'Day 3', time: '07:30 AM', title: 'Mahodand Lake Excursion', activities: ['Jeep ride to Mahodand Lake', 'Full day lakeside picnic', 'Return to Mingora'] },
      { day: 'Day 4', time: '08:00 AM', title: 'Return to Islamabad', activities: ['Morning departure from Swat', 'Arrive Rawalpindi by evening'] },
    ],
    price: 250,
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=1920&q=80',
  },
]

export const defaultHotels = [
  {
    id: '1',
    name: 'Serena Hotel Gilgit',
    location: 'Gilgit, Gilgit-Baltistan',
    rating: 4.8,
    pricePerNight: 15000,
    description: 'Luxury accommodation with stunning mountain views and world-class amenities.',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
  },
  {
    id: '2',
    name: 'Eagle Nest Resort',
    location: 'Duikar, Hunza',
    rating: 4.9,
    pricePerNight: 12000,
    description: 'Breathtaking sunrise views over Rakaposhi and Ultar Sar peaks.',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
  },
  {
    id: '3',
    name: 'Shangrila Resort',
    location: 'Skardu',
    rating: 4.7,
    pricePerNight: 18000,
    description: 'Iconic resort on Lower Kachura Lake with heart-shaped lake views.',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
  },
  {
    id: '4',
    name: 'Pearl Continental Murree',
    location: 'Murree, Punjab',
    rating: 4.6,
    pricePerNight: 10000,
    description: 'Premium hill station hotel surrounded by pine forests and cool mountain air.',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
  },
]

export const popularPlaces = [
  {
    id: 'hunza',
    name: 'Hunza',
    description: 'Ancient forts, cherry blossoms, and the legendary Karakoram Highway.',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&q=80',
  },
  {
    id: 'skardu',
    name: 'Skardu',
    description: "Gateway to the world's highest peaks and crystal-clear alpine lakes.",
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
  },
  {
    id: 'naran',
    name: 'Naran',
    description: 'Home to the legendary Saif ul Malook Lake and Babusar Pass.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
  },
  {
    id: 'swat',
    name: 'Swat',
    description: 'Emerald valleys, Buddhist heritage, and the Malam Jabba ski resort.',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&q=80',
  },
  {
    id: 'murree',
    name: 'Murree',
    description: "Pakistan's favorite hill station with colonial charm and pine forests.",
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
  },
  {
    id: 'fairy-meadows',
    name: 'Fairy Meadows',
    description: 'A magical meadow at the base of Nanga Parbat, the Killer Mountain.',
    image: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&q=80',
  },
  {
    id: 'nanga-parbat',
    name: 'Nanga Parbat',
    description: 'The ninth highest mountain in the world with dramatic alpine scenery.',
    image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&q=80',
  },
]

export const features = [
  { icon: '🛡️', title: 'Trusted Travel Services', description: 'Licensed and verified travel agency with years of experience.' },
  { icon: '🧭', title: 'Experienced Tour Guides', description: 'Local experts who know every trail, culture, and hidden gem.' },
  { icon: '🎒', title: 'Best Tour Packages', description: "Curated itineraries covering Pakistan's most stunning destinations." },
  { icon: '🏨', title: 'Comfortable Hotels', description: 'Handpicked accommodations for a restful stay after adventure.' },
  { icon: '💰', title: 'Affordable Prices', description: 'Competitive rates without compromising on quality or comfort.' },
  { icon: '📞', title: '24/7 Customer Support', description: 'Round-the-clock assistance before, during, and after your trip.' },
]

export const reviews = [
  {
    id: '1',
    name: 'Ahmed Khan',
    rating: 5,
    text: 'Pehchaan Travels made our Hunza trip absolutely unforgettable. Everything was perfectly organized!',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
  },
  {
    id: '2',
    name: 'Fatima Ali',
    rating: 5,
    text: 'Professional team, great hotels, and amazing tour guides. Highly recommend for Northern Pakistan tours.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
  },
  {
    id: '3',
    name: 'Usman Malik',
    rating: 4,
    text: 'Custom trip to Skardu was exactly what we wanted. Pehchaan Travels listened to every detail.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&q=80',
  },
]

export const HERO_IMAGE = 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1920&q=85'
export const TRIP_IMAGE = 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1920&q=80'
export const PHONE_NUMBER = '+92 3264828913'
export const EMAIL = 'info@pehchaantravels.com'
export const ADDRESS = 'Main Boulevard, Islamabad, Pakistan'

